# Site wide configuration

title: Waleed Ashraf
locale: en_US
description: All my writings comes here.
logo: site-logo.png
search: true
url: https://waleedashraf.me

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Waleed Ashraf
  avatar: avatar_face.png
  email: hy@waleedashraf.me
  disqus-shortname:
  twitter: waleedashraf01
  facebook: waleedashraf01
  github: waleedashraf
  stackexchange: http://stackoverflow.com/users/5691769/waleed-ashraf
  linkedin: waleedashraf01
  instagram: waleedashrafhere
  flickr: waleedashraf
  tumblr: waleedashraf
  pinterest: #username
  weibo: #userid
  behance: waleed_ashraf
  google:
    plus: WaleedAshrafhere
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
